# Generated by Django 4.0.5 on 2022-06-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
